version: '3.8'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  svc:
    container_name: grpc_svc
    restart: always
    depends_on:
      - db
    build: .
    ports:
      - 9001:9001
    links:
      - db
