// Code generated by "stringer -type=Direction -trimprefix=Direction"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DirectionNorth-1]
	_ = x[DirectionNorthWest-2]
	_ = x[DirectionWest-4]
	_ = x[DirectionSouthWest-8]
	_ = x[DirectionSouth-16]
	_ = x[DirectionSouthEast-32]
	_ = x[DirectionEast-64]
	_ = x[DirectionNorthEast-128]
}

const (
	_Direction_name_0 = "NorthNorthWest"
	_Direction_name_1 = "West"
	_Direction_name_2 = "SouthWest"
	_Direction_name_3 = "South"
	_Direction_name_4 = "SouthEast"
	_Direction_name_5 = "East"
	_Direction_name_6 = "NorthEast"
)

var (
	_Direction_index_0 = [...]uint8{0, 5, 14}
)

func (i Direction) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Direction_name_0[_Direction_index_0[i]:_Direction_index_0[i+1]]
	case i == 4:
		return _Direction_name_1
	case i == 8:
		return _Direction_name_2
	case i == 16:
		return _Direction_name_3
	case i == 32:
		return _Direction_name_4
	case i == 64:
		return _Direction_name_5
	case i == 128:
		return _Direction_name_6
	default:
		return "Direction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
