// Code generated by "stringer -type=Direction"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DirectionNorth-1]
	_ = x[DirectionEast-2]
	_ = x[DirectionWest-4]
	_ = x[DirectionSouth-8]
}

const (
	_Direction_name_0 = "DirectionNorthDirectionEast"
	_Direction_name_1 = "DirectionWest"
	_Direction_name_2 = "DirectionSouth"
)

var (
	_Direction_index_0 = [...]uint8{0, 14, 27}
)

func (i Direction) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Direction_name_0[_Direction_index_0[i]:_Direction_index_0[i+1]]
	case i == 4:
		return _Direction_name_1
	case i == 8:
		return _Direction_name_2
	default:
		return "Direction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
