// Code generated by "stringer -type=Status"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusPending-1]
	_ = x[StatusActive-2]
	_ = x[StatusInactive-3]
	_ = x[StatusDeleted-4]
}

const _Status_name = "StatusPendingStatusActiveStatusInactiveStatusDeleted"

var _Status_index = [...]uint8{0, 13, 25, 39, 52}

func (i Status) String() string {
	i -= 1
	if i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
