// Code generated by "stringer -type=Status -trimprefix=Status"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusPending-0]
	_ = x[StatusActive-1]
	_ = x[StatusInactive-2]
	_ = x[StatusDeactivated-3]
}

const _Status_name = "PendingActiveInactiveDeactivated"

var _Status_index = [...]uint8{0, 7, 13, 21, 32}

func (i Status) String() string {
	if i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
