// Code generated by "stringer -type=Role -trimprefix=Role"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RoleUnknown-0]
	_ = x[RoleGuest-1]
	_ = x[RoleMember-2]
	_ = x[RoleModerator-3]
	_ = x[RoleAdmin-4]
}

const _Role_name = "UnknownGuestMemberModeratorAdmin"

var _Role_index = [...]uint8{0, 7, 12, 18, 27, 32}

func (i Role) String() string {
	if i >= Role(len(_Role_index)-1) {
		return "Role(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Role_name[_Role_index[i]:_Role_index[i+1]]
}
