// Code generated by "stringer -type=Sport"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Baseball-1]
	_ = x[Soccer-2]
	_ = x[Boxing-3]
	_ = x[Tennis-4]
	_ = x[Hockey-5]
}

const _Sport_name = "UnknownBaseballSoccerBoxingTennisHockey"

var _Sport_index = [...]uint8{0, 7, 15, 21, 27, 33, 39}

func (i Sport) String() string {
	if i < 0 || i >= Sport(len(_Sport_index)-1) {
		return "Sport(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Sport_name[_Sport_index[i]:_Sport_index[i+1]]
}
