// Code generated by "stringer -type=State"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Start-1]
	_ = x[Progressing-2]
	_ = x[Success-3]
	_ = x[Fail-4]
}

const _State_name = "StartProgressingSuccessFail"

var _State_index = [...]uint8{0, 5, 16, 23, 27}

func (i State) String() string {
	i -= 1
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
